# Generated by Django 4.0.2 on 2022-03-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assignedby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), related_name='created_by', to='todoapi.user'),
        ),
    ]
